#:schema node_modules/wrangler/config-schema.json
name = "cf-owntracks"
main = "src/index.ts"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

# Bind an R2 Bucket. Use R2 to store arbitrarily large blobs of data, such as files.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#r2-buckets
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "cf-owntracks"

[vars]
BASIC_AUTH_USER = "111"
BASIC_AUTH_PASS = "111"

# Bind a KV Namespace. Use KV as a simple key-value store.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#kv-namespaces
[[kv_namespaces]]
binding = "LAST_LOCATIONS"
id = "79f37c45ce864cbf82f5ce573b07ae06"
